alter table  wy_bse_customer add parent_id int default 0  comment '父租户ID' after cus_type;
alter table wy_bse_customer_invoice add title varchar(128) default null after cus_id
CREATE TABLE `wy_bse_tenant_share` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `tenant_id` int(11) NOT NULL DEFAULT '0' COMMENT '租户id',
  `contract_id` int(11) NOT NULL DEFAULT '0' COMMENT '合同ID',
  `fee_type` tinyint(4) NOT NULL DEFAULT '0' COMMENT '分摊费用类型1租金2管理费3固定费用',
  `share_type` tinyint(4) NOT NULL DEFAULT '1' COMMENT '1面积2比例',
  `share_num` decimal(11,2) NOT NULL DEFAULT '0.00' COMMENT '分摊数量',
  `share_rate` int NOT NULL DEFAULT 0 COMMENT '分摊比例',
  `share_amount` decimal(10,2) NOT NULL DEFAULT '1' COMMENT '分摊金额',
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `deleted_at` datetime DEFAULT NULL,
  `c_uid` int(11) DEFAULT NULL COMMENT '创建人',
  `u_uid` int(11) DEFAULT NULL COMMENT '更新人',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_id` (`tenant_id`),
  KEY `contract_id` (`contract_id`)
)

create table wy_bse_tenant(
  id int not null auto_increment,
  company_id int not null default 0 comment '公司id',
  proj_id  int not null default 0 comment '项目ID',
  name varchar(128) not null default '' comment '租户名称',
  business_id int default 0 comment '工商信息id',
  checkin_time date default null comment '入住时间',
  industry varchar(64) default '' comment '行业',
  level  varchar(32) default '' comment '租户级别',
  nature varchar(32) default '' comment '性质',
  worker_num varchar(8) default '' comment '员工人数',
  remark varchar(1024) default '' comment '备注',
  heating_area decimal(8,2) default 0.00 comment '取暖面积',
  heating_amount decimal(11,2) default 0.00 comment '取暖金额',
  pay_method tinyint not null default 1 comment '支付周期',
  c_uid int default 0 comment '新增用户ID',
  u_uid int default 0 comment '更新用户ID',
  created_at datetime default null,
  updated_at datetime default null,
  primary key (id),
  key idx_cus_id(company_id,name));
)


CREATE TABLE `wy_bse_parking_lot` (
  id int not null auto_increment,
  company_id int not null default 0 comment '公司id',
  proj_id  int not null default 0 comment '项目ID',
  parking_name varchar(128) default null comment '停车场名称',
  `lot_no` varchar(255) DEFAULT NULL COMMENT '车位名称',
  `tenant_id` int DEFAULT NULL COMMENT '租户ID',
  `tenant_name` varchar(255) DEFAULT NULL COMMENT '商（租）户名称',
  `rent_begin` date DEFAULT NULL COMMENT '起租时间',
  `rent_end` date DEFAULT NULL COMMENT '退租时间',
  `rent_type` varchar(50) DEFAULT NULL COMMENT '租赁类型 新租/续租',
  `month_price` decimal(10,2) DEFAULT NULL COMMENT '月费率',
  `renter_name` varchar(255) DEFAULT NULL COMMENT '车主姓名',
  `renter_phone` varchar(50) DEFAULT NULL COMMENT '联系电话',
  `car_no` varchar(256) DEFAULT NULL COMMENT '车牌号',
  `charge_date` date DEFAULT NULL COMMENT '缴费日期',
  `rent_month` smallint(11) DEFAULT NULL COMMENT '租赁时长/月',
  `amount` decimal(10,2) DEFAULT NULL COMMENT '金额',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  `created_at` datetime DEFAULT NULL COMMENT '创建时间',
  `c_uid` int DEFAULT NULL COMMENT '创建人',
  `updated_at` datetime DEFAULT NULL COMMENT '更新时间',
  `u_uid` int DEFAULT NULL COMMENT '更新人',
  PRIMARY KEY (`id`),
  key(company_id,proj_id),
  key(company_id,tenant_name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='车位';


CREATE TABLE `wy_bse_equipment_maintain` (
  id int not null auto_increment,
  company_id int not null default 0 comment '公司id',
  proj_id  int not null default 0 comment '项目ID',
  device_name varchar(500) DEFAULT NULL COMMENT '设备名',
  model varchar(50) DEFAULT NULL COMMENT '类型',
  major varchar(50) DEFAULT NULL COMMENT '专业',
  position varchar(128) DEFAULT NULL COMMENT '位置',
  maintain_period varchar(128) DEFAULT NULL COMMENT '维护周期',
  equipment_id  int not null default 0 comment '设备ID',
  equipment_type varchar(128) DEFAULT NULL COMMENT '设备类型',
  maintain_content varchar(512) DEFAULT NULL COMMENT '维护内容',
  maintain_date datetime  COMMENT '维护时间',
  maintain_person varchar(30) DEFAULT NULL COMMENT '维护人',
  quantity int DEFAULT NULL COMMENT '维护数量',
  maintain_type varchar(128) DEFAULT NULL COMMENT '维护类型',
  pic varchar(1024) DEFAULT NULL COMMENT '维护图片',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  `created_at` datetime DEFAULT NULL COMMENT '创建时间',
  `c_uid` int DEFAULT NULL COMMENT '创建人',
  `updated_at` datetime DEFAULT NULL COMMENT '更新时间',
  `u_uid` int DEFAULT NULL COMMENT '更新人',
  PRIMARY KEY (`id`)
)

wy_bse_inspection(
  id int not null auto_increment,
  company_id int not null default 0 comment '公司id',
  proj_id  int not null default 0 comment '项目ID',
  name  varchar(500) DEFAULT NULL COMMENT '名称',
   type int not null default 0 comment '巡检类型',
   qr_code varchar(500) DEFAULT NULL COMMENT '二维码',
   device_name varchar(500) DEFAULT NULL COMMENT '设备名称',
   position varchar(500) DEFAULT NULL COMMENT '位置',
   check_cycle int DEFAULT NULL COMMENT '位置',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  `created_at` datetime DEFAULT NULL COMMENT '创建时间',
  `c_uid` int DEFAULT NULL COMMENT '创建人',
  `updated_at` datetime DEFAULT NULL COMMENT '更新时间',
  `u_uid` int DEFAULT NULL COMMENT '更新人',
  PRIMARY KEY (`id`))

CREATE TABLE  wy_bse_inspection_record(
  id int not null auto_increment,
  company_id int not null default 0 comment '公司id',
  proj_id  int not null default 0 comment '项目ID',
  inspection_id   int not null default 0 comment '维护ID',
  is_unusual  int not null default 0 comment '日常',
  pic varchar(500) DEFAULT NULL COMMENT '维护图片',
  c_username varchar(500) DEFAULT NULL COMMENT '创建人',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  `created_at` datetime DEFAULT NULL COMMENT '创建时间',
  `c_uid` int DEFAULT NULL COMMENT '创建人',
  `updated_at` datetime DEFAULT NULL COMMENT '更新时间',
  `u_uid` int DEFAULT NULL COMMENT '更新人',
  PRIMARY KEY (`id`))

CREATE TABLE  wy_bse_workorder(
   id int not null auto_increment,
  company_id int not null default 0 comment '公司id',
  proj_id  int not null default 0 comment '项目ID',
   workorder_no varchar(64) DEFAULT '' comment '工单编号',
   open_time datetime DEFAULT null comment '开单时间',
   tenant_id int not null default 0 comment '租户ID',
tenant_name  varchar(128) DEFAULT '' comment '租户名称',
building_floor_room  varchar(128) DEFAULT '' comment '楼层编号',
position  varchar(128) DEFAULT '' comment '位置',
open_person  varchar(128) DEFAULT '' comment '开单人',
open_phone  varchar(128) DEFAULT '' comment '开单联系人电话',
repair_content varchar(128) DEFAULT '' comment '保修内容',
pic  varchar(128) DEFAULT '' comment '报修图片',
order_source varchar(128) DEFAULT '' comment '开单来源',
status tinyint  not null default 1 comment '工单状态',
order_time datetime DEFAULT null comment '接单时间',
order_uid int not null default 0 comment '接单人ID',
order_person  varchar(128) DEFAULT '' comment '接单人',
return_time datetime DEFAULT null comment '关闭工单时间',
close_person varchar(128) DEFAULT '' comment '关闭工单人员',
time_used double(10,2) DEFAULT 0.00 comment '用时小时',
engineering_type int not null default 0 comment '工程类型',
charge_amount double(10,2) DEFAULT 0.00 comment '费用',
process_result varchar(128) DEFAULT '' comment '处理结果',
maintain_pic varchar(512) DEFAULT '' comment '维修图片',
maintain_person varchar(128) DEFAULT '' comment '维修人',
rate varchar(32) DEFAULT null comment '评价',
`remark` varchar(500) DEFAULT NULL COMMENT '备注',
  `created_at` datetime DEFAULT NULL COMMENT '创建时间',
  `c_uid` int DEFAULT NULL COMMENT '创建人',
  `updated_at` datetime DEFAULT NULL COMMENT '更新时间',
  `u_uid` int DEFAULT NULL COMMENT '更新人',
  PRIMARY KEY (`id`))


create table wy_bse_workorder_log(
   id int not null auto_increment,
workorder_id int not null ,
status int,
c_username  varchar(128) DEFAULT '' comment '处理人',
`remark` varchar(500) DEFAULT NULL COMMENT '备注',
  `created_at` datetime DEFAULT NULL COMMENT '创建时间',
  `c_uid` int DEFAULT NULL COMMENT '创建人',
  `updated_at` datetime DEFAULT NULL COMMENT '更新时间',
  `u_uid` int DEFAULT NULL COMMENT '更新人',
  PRIMARY KEY (`id`)
)

create table wy_bse_invoice(
  id int not null auto_increment,
  company_id int not null default 0 comment '公司id',
  tenant_id int not null default 0 comment '租户ID',
  title varchar(128) default null comment 'title',
  tax_number varchar(128) default null comment '税号',
  bank_name varchar(128) default null comment '银行名称',
  account_name varchar(128) default null comment '银行账号',
  addr varchar(128) default null comment '地址',
  tel_number varchar(128) default null comment '电话',
  invoice_type tinyint default 0 comment '发票类型',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  `created_at` datetime DEFAULT NULL COMMENT '创建时间',
  `c_uid` int DEFAULT NULL COMMENT '创建人',
  `updated_at` datetime DEFAULT NULL COMMENT '更新时间',
  `u_uid` int DEFAULT NULL COMMENT '更新人',
   delete_at  datetime DEFAULT NULL COMMENT '删除时间',
  PRIMARY KEY (`id`))


CREATE TABLE `wy_bse_tenant_share` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  company_id int not null default 0 comment '公司ID',
  proj_id  int not null default 0 comment '项目ID',
  `tenant_id` int(11) NOT NULL DEFAULT '0' COMMENT '租户id',
  `name` varchar(128) NOT NULL DEFAULT '0' COMMENT '分摊公司名称',
  `share_rental_type` tinyint(4) NOT NULL DEFAULT '1' COMMENT '租金分摊方式1面积2比例',
  `rental_ratio` tinyint(4) NOT NULL DEFAULT '0' COMMENT '租金比例百分比存整数',
  rental_area  decimal(11,2) NOT NULL DEFAULT '0.00' COMMENT '分摊面积',
  `share_rental_type` tinyint(4) NOT NULL DEFAULT '1' COMMENT '管理费分摊方式1面积2比例',
  `manager_ration` int(11) NOT NULL DEFAULT '0' COMMENT '管理费分摊比例',
  `manager_area` decimal(11,2) NOT NULL DEFAULT '0.00' COMMENT '管理费分摊面积',
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `deleted_at` datetime DEFAULT NULL,
  `c_uid` int(11) DEFAULT NULL COMMENT '创建人',
  `u_uid` int(11) DEFAULT NULL COMMENT '更新人',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_id` (`parent_tenant_id`)
) comment '租户分摊表';


CREATE TABLE `wy_bse_wx_user` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  company_id int not null default 0 comment '公司ID',
  user_id int not null default 0 comment '用户iD',
 name varchar(128)  DEFAULT '',
 email varchar(128) DEFAULT '',
 email_verified_at varchar(128) DEFAULT '0',
 username varchar(128) DEFAULT '',
 phone varchar(128) DEFAULT '',
 avatar varchar(512) DEFAULT '',
 weapp_openid varchar(128) DEFAULT '',
 nickname varchar(128) DEFAULT '',
 weapp_avatar varchar(128) DEFAULT '',
 country varchar(128) DEFAULT '',
 province varchar(128) DEFAULT '',
 city varchar(128) DEFAULT '',
 language varchar(128) DEFAULT '',
 location varchar(128) DEFAULT '',
 gender varchar(128) DEFAULT '',
 level varchar(128) DEFAULT '',
 is_admin varchar(128) DEFAULT '',
 `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `deleted_at` datetime DEFAULT NULL,
  `c_uid` int(11) DEFAULT NULL COMMENT '创建人',
  `u_uid` int(11) DEFAULT NULL COMMENT '更新人',
  PRIMARY KEY (`id`))




CREATE TABLE `wy_bse_tenant_contract` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `company_id` int(11) NOT NULL DEFAULT '0' COMMENT '公司id',
  `proj_id` int(11) NOT NULL DEFAULT '0' COMMENT '租赁期限（月）',
  `tenant_id` int(11) NOT NULL DEFAULT '0' COMMENT '租户',
  `contract_no` varchar(64) NOT NULL DEFAULT '' COMMENT '合同编号',
  `contract_type` int(1) NOT NULL DEFAULT '0' COMMENT '合同类型1 新签 2 续签',
  `rental_price` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT '签约单价',
  `rental_price_type` tinyint(4) DEFAULT '1' COMMENT '1:天 2 月',
  `rental_month_amount` decimal(10,2) DEFAULT NULL COMMENT '月租金金额',
  `management_price` decimal(10,0) DEFAULT '0' COMMENT '管理费单价',
  `management_month_amount` decimal(10,2) DEFAULT NULL COMMENT '月管理费金额',
  `violate_rate` smallint(4) NOT NULL DEFAULT '0' COMMENT '违约金比例',
  `sign_date` date NOT NULL COMMENT '签约日期',
  `pay_method` smallint(6) NOT NULL DEFAULT '0' COMMENT '支付周期',
  `contract_state` tinyint(4) NOT NULL DEFAULT '0' COMMENT '1正在执行2退租',
  `start_date` date NOT NULL COMMENT '起始日期',
  `lease_term` smallint(6) NOT NULL DEFAULT '0' COMMENT '租赁期限（月）',
  `end_date` date NOT NULL COMMENT '结束日期',
  `sign_area` varchar(64) NOT NULL DEFAULT '' COMMENT '签约面积',
  `rental_deposit_amount` decimal(10,2) DEFAULT '0.00' COMMENT '租赁押金金额',
  `rental_deposit_month` smallint(6) DEFAULT NULL COMMENT '几个月租金作为押金',
  `increase_year` smallint(6) DEFAULT '0' COMMENT '第几年开始递增',
  `increase_date` date DEFAULT NULL COMMENT '递增时间',
  `increase_rate` smallint(6) DEFAULT '0' COMMENT '递增率，单价递增',
  `bill_day` smallint(6) DEFAULT '1' COMMENT '账单日',
  `bill_type` tinyint(4) NOT NULL DEFAULT '1' COMMENT '1正常账单免租期算账单里面，2 遇见免租期帐期后延',
  `ahead_pay_month` smallint(6) DEFAULT '0' COMMENT '提前几个月收款',
  `manager_deposit_month` tinyint(4) DEFAULT '0' COMMENT '几个月管理费作为管理押金',
  `manager_deposit_amount` decimal(10,2) DEFAULT '0.00' COMMENT '管理费押金金额',
  `increase_show` tinyint(4) DEFAULT '0' COMMENT '递增',
  `manager_show` tinyint(4) DEFAULT '0' COMMENT '管理',
  `rental_usage` varchar(16) DEFAULT '' COMMENT '租赁用途',
  `leaseback_date` date DEFAULT NULL COMMENT '退租时间',
  `free_type` tinyint(4) DEFAULT '1' COMMENT '免租类型 0 没有免租 1 按月 2按天',
  `room_type` tinyint(4) DEFAULT '1' COMMENT '房源编号1 房源2 工位 ',
  `c_uid` int(11) DEFAULT '0' COMMENT '创建用户ID',
  `u_uid` int(11) DEFAULT '0' COMMENT '更新用户ID',
  `created_at` datetime DEFAULT NULL COMMENT '创建时间',
  `updated_at` datetime DEFAULT NULL COMMENT '更新时间',
  `deleted_at` datetime DEFAULT NULL COMMENT '删除时间',
  PRIMARY KEY (`id`),
  KEY `company_id_2` (`company_id`,`tenant_id`),
  KEY `idx_signdate` (`company_id`,`sign_date`),
  KEY `idx_enddate` (`end_date`)
)